[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Onboard Data Python Client API"
authors = [{name = "Ted Alexander", email = "ted.alexander@onboarddata.io"}]
dynamic = ["version", "description"]
